# Generated by Django 6.0 on 2025-12-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Herbal Oil Product'),
            preserve_default=False,
        ),
    ]
